### PR TITLE
content update

### PR DESCRIPTION
**Pull request by Favy-source**
This branch is still in progress but you can take a look at the work so far and tell me if there is any need for corrections.
Thank you

### CODE REVIEW

**Comment by Favy-source** [comment]
New update   2

**Review by Favy-source — COMMENTED** [review]
More content uploaded for review @konfirmed

**Review by konfirmed — COMMENTED** [review]
@Favy-source The names of the festival's should be updated in my opinion 
image

**Comment by Favy-source** [comment]
Those are what they are called traditionally
How do you suggest I go about it? @konfirmed

**Comment by Favy-source** [comment]
Would have spaced them but it's an mdx file

**Comment by konfirmed** [comment]
@Favy-source what's the update on this PR

**Pull request merged**
